name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up NVIDIA CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.22      
      with:
        cuda: '12.5.0'

    - name: Verify CUDA installation
      run: nvcc --version
      
    - name: Run tests
      run: make clean run_tests
